### ISSUE TITLE
Python program from README crashes

### ISSUE THREAD

**Issue by yurivict** [lucasb-eyer/heatmap#11]
The crashing line:
> libhm.heatmap_add_point(hm, c_ulong(x), c_ulong(y))

Found on FreeBSD 11.1

**Comment by lucasb-eyer** [comment]
Yes, thank you for the report. It seems to be the same thing as [I mentioned here for windows](https://github.com/lucasb-eyer/heatmap/issues/7#issuecomment-268073365), namely that the types must be annotated.

I will add the type annotations to the readme and example file later today.

**Comment by lucasb-eyer** [comment]
PS: I really don't understand why it worked without in the past, but on modern systems (py? gcc?), they are necessary. If someone knows, I'd love to hear why.

**Comment by lucasb-eyer** [comment]
Done, please let me know if you still experience the crash.
