### ISSUE TITLE
Processing Intergration

### ISSUE THREAD

**Issue by davidbambalan** [lucasb-eyer/heatmap#14]
Can I use this library on Processing ([https://processing.org/](url))?

**Comment by lucasb-eyer** [comment]
Hi, I completely missed this issue! Sure, if processing is able to interface with C functions, you should be able to use it no problem! I specifically decided to write it in pure C such that it can be called from all kinds of languages. If you are still interested in trying this, please let me know how it goes. Closing the issue for now, but feel free to re-open with concrete problems if you encounter some.
