### ISSUE TITLE
How to overlay heatmap on an image?

### ISSUE THREAD

**Issue by mirzafahad** [lucasb-eyer/heatmap#15]
Hi Lucas,

Thanks for this great library. I have a quick question about the first image from your Readme. How did you overlay the heatmap on the DOTA map?

Regards,
Fahad Mirza

**Comment by lucasb-eyer** [comment]
Hi, since the rendered heatmap does contain alpha channel (as long as the colormap contained it, which the default ones do) it's simply alpha-blending on top of the image. You could do that in any image editing program.
