### ISSUE TITLE
Support for weighted data points

### ISSUE THREAD

**Issue by arunkumar-ra** [lucasb-eyer/heatmap#5]
Hi Lucas,

Can you add support for creating heat maps with data sets where each point has an associated weight?

Thanks,
Arunkumar R.

**Comment by lucasb-eyer** [comment]
That's a good feature to have, I will add that feature soon-ish.

**Comment by lucasb-eyer** [comment]
A little late because I'm on vacation, but it's now supported [via the API](https://github.com/lucasb-eyer/heatmap/#using-weighted-datapoints) and in the [example commandline tool](https://github.com/lucasb-eyer/heatmap/#using-without-programming).

**Comment by lucasb-eyer** [comment]
Hi Arunkumar,

Just in case you didn't notice, I added that:
https://github.com/lucasb-eyer/heatmap/issues/5
​
Cheers,
Lucas

**Comment by arunkumar-ra** [comment]
Hi Lucas,
This is great! Thank you very much.
